### ISSUE TITLE
Асинхронное выполнение запросов

### ISSUE THREAD

**Issue by 0nkery** [klen/muffin-peewee#3]
В демо-приложении в основном репо был пример с асинхронным выполнением запросов к БД. В muffin_peewee.plugin.Plugin методы query и run закомментированы. Почему?

**Comment by klen** [comment]
Привет, на текущий момент асинхронные запросы к бд не поддерживаются. Если есть такая необходимость можно использовать, что нибудь вроде aiopg/aio-peewee. Также можно написать новый плагин или модернизировать этот.
