### ISSUE TITLE
Async queries

### ISSUE THREAD

**Issue by mrbox** [klen/muffin-peewee#8]
Hi @klen!

It's not really an issue report but a question. I see that db connections are handled asynchronously- that's great but I don't see anywhere that you await db queries- are they synchronous? I'm curious mostly because of benchmark that you made- seems cool but I'd like to understand why ?sync? queries doesn't choke the app.

Cheers!

**Comment by serathius** [comment]
I think you would need https://github.com/05bit/peewee-async

**Comment by serathius** [comment]
I created solution myself, but I dropped some features of this library I created my own, because I didn't want downgrade work of author. https://github.com/serathius/muffin-peewee-async
